.\Man page for AstroCTC
.TH AstroCTC 1 2016-03-18
.SH NAME
astroctc \- A Planetary and Lunar imaging program (GTK+, GStreamer, V4L2)
.SH SYNOPSIS
.B astroctc
.SH DESCRIPTION
\fBastroctc\fR (Astronomy CCD in Telescope Capture) is designed for video and 
image capture of the Planets and the Moon. A dedicated or modified astronomy 
device will give the best results, however it should work with any device
as long as the driver is Video4Linux2 compliant.

Numerous video and image formats are available, however only basic FITS support is
provided.

While astroctc is primarily for use in astronomy, it also serves well as a general
viewing program.
.SH OPTIONS
astroctc has no options
.SH EXIT STATUS
On success astroctc will exit(0); on error it will exit(-1). Futher details will
be in the log file.
.SH FILES
.TP
$HOME/.AstroCTC/AstroCTC.log 
Logs all messages, errors, events (viewable in GUI)
.TP
$HOME/.AstroCTC/cam_info
Capabilities of the latest device used (viewable in GUI)
.TP
$HOME/.AstroCTC/user_preferences
Application preferences (set up in GUI)
.TP
$HOME/.AstroCTC/Profiles
Preset Profile settings may be named and saved within the GUI.
All will stored in the Profiles directory. (viewable in GUI)
.TP
$HOME/.AstroCTC/Profiles/Last_Session
Settings used in previous session. (default profile in GUI)
.TP
$HOME/AstroCTC_Captures
Default directory to store captures (configurable in GUI)
.SH BUGS
On some computers and some cameras (and sometimes), changing the resolution of the 
video area will work the first time, but subsequent changes will be unpredictabe. 
The work-around is to select 'Camera' -> 'Restart Video' on the menu.

There is an occasional error when astroctc is run for the first time in a session 
where the program aborts with a core dump. This appears to be a problem with the 
driver and the camera not being ready. Running again usually works, but the transient 
nature makes this difficult to narrow down.
.SH AUTHOR
astroctc and this manual page were written by Anthony Buckley <astroctc_AB@gmail.com>
